
# Site settings
title: Sophia Lou
email: sophialou17@gmail.com
url: https://sophialou.github.io
description: "I'm Sophia. Come learn more about me."

# Color settings
color:
  primary-dark: '#000000'
  links: '#fff'

social:
  - title: linkedin
    url: https://linkedin.com/in/sophialou
  - title: github
    url: https://github.com/sophialou

blog: https://medium.com/@sophialou

# Build settings
markdown: kramdown
permalink: pretty
